# This script was written and developed by ABKGroup students at UCSD. However, the underlying commands and reports are copyrighted by Cadence.
# We thank Cadence for granting permission to share our research to help promote and foster the next generation of innovators.
source macro_rpt/PU0_PE7.tcl
source macro_rpt/PU0_PE6.tcl
source macro_rpt/PU0_PE5.tcl
source macro_rpt/PU0_PE4.tcl
source macro_rpt/PU0_PE3.tcl
source macro_rpt/PU0_PE2.tcl
source macro_rpt/PU0_PE1.tcl
source macro_rpt/PU0_PE0.tcl
source macro_rpt/PU0_slave.tcl
source macro_rpt/PU2_PE7.tcl
source macro_rpt/PU2_PE6.tcl
source macro_rpt/PU2_PE5.tcl
source macro_rpt/PU2_PE4.tcl
source macro_rpt/PU2_PE3.tcl
source macro_rpt/PU2_PE2.tcl
source macro_rpt/PU2_PE1.tcl
source macro_rpt/PU2_PE0.tcl
source macro_rpt/PU2_slave.tcl
source macro_rpt/PU4_PE7.tcl
source macro_rpt/PU4_PE6.tcl
source macro_rpt/PU4_PE5.tcl
source macro_rpt/PU4_PE4.tcl
source macro_rpt/PU4_PE3.tcl
source macro_rpt/PU4_PE2.tcl
source macro_rpt/PU4_PE1.tcl
source macro_rpt/PU4_PE0.tcl
source macro_rpt/PU4_slave.tcl
source macro_rpt/PU1_PE7.tcl
source macro_rpt/PU1_PE6.tcl
source macro_rpt/PU1_PE5.tcl
source macro_rpt/PU1_PE4.tcl
source macro_rpt/PU1_PE3.tcl
source macro_rpt/PU1_PE2.tcl
source macro_rpt/PU1_PE1.tcl
source macro_rpt/PU1_PE0.tcl
source macro_rpt/PU1_slave.tcl
source macro_rpt/PU3_PE7.tcl
source macro_rpt/PU3_PE6.tcl
source macro_rpt/PU3_PE5.tcl
source macro_rpt/PU3_PE4.tcl
source macro_rpt/PU3_PE3.tcl
source macro_rpt/PU3_PE2.tcl
source macro_rpt/PU3_PE1.tcl
source macro_rpt/PU3_PE0.tcl
source macro_rpt/PU3_slave.tcl
source macro_rpt/PU5_PE7.tcl
source macro_rpt/PU5_PE6.tcl
source macro_rpt/PU5_PE5.tcl
source macro_rpt/PU5_PE4.tcl
source macro_rpt/PU5_PE3.tcl
source macro_rpt/PU5_PE2.tcl
source macro_rpt/PU5_PE1.tcl
source macro_rpt/PU5_PE0.tcl
source macro_rpt/PU5_slave.tcl
source macro_rpt/PU6_PE3.tcl
source macro_rpt/PU6_PE2.tcl
source macro_rpt/PU6_PE1.tcl
source macro_rpt/PU6_PE0.tcl
source macro_rpt/PU6_PE4.tcl
source macro_rpt/PU6_PE5.tcl
source macro_rpt/PU6_PE6.tcl
source macro_rpt/PU6_PE7.tcl
source macro_rpt/PU6_slave.tcl
source macro_rpt/PU7_PE0.tcl
source macro_rpt/PU7_PE1.tcl
source macro_rpt/PU7_PE2.tcl
source macro_rpt/PU7_PE3.tcl
source macro_rpt/PU7_PE5.tcl
source macro_rpt/PU7_PE4.tcl
source macro_rpt/PU7_PE7.tcl
source macro_rpt/PU7_PE6.tcl
source macro_rpt/PU7_slave.tcl
source macro_rpt/read_buf.tcl
source macro_rpt/write_buf.tcl
