# This script was written and developed by ABKGroup students at UCSD. However, the underlying commands and reports are copyrighted by Cadence.
# We thank Cadence for granting permission to share our research to help promote and foster the next generation of innovators.
source macro_rpt/PU0_PE15.tcl
source macro_rpt/PU0_PE14.tcl
source macro_rpt/PU0_PE13.tcl
source macro_rpt/PU0_PE12.tcl
source macro_rpt/PU0_PE11.tcl
source macro_rpt/PU0_PE10.tcl
source macro_rpt/PU0_PE9.tcl
source macro_rpt/PU0_PE8.tcl
source macro_rpt/PU0_PE7.tcl
source macro_rpt/PU0_PE6.tcl
source macro_rpt/PU0_PE5.tcl
source macro_rpt/PU0_PE4.tcl
source macro_rpt/PU0_PE3.tcl
source macro_rpt/PU0_PE2.tcl
source macro_rpt/PU0_PE1.tcl
source macro_rpt/PU0_PE0.tcl
source macro_rpt/PU0_slave.tcl
source macro_rpt/PU1_PE15.tcl
source macro_rpt/PU1_PE14.tcl
source macro_rpt/PU1_PE13.tcl
source macro_rpt/PU1_PE12.tcl
source macro_rpt/PU1_PE11.tcl
source macro_rpt/PU1_PE10.tcl
source macro_rpt/PU1_PE9.tcl
source macro_rpt/PU1_PE8.tcl
source macro_rpt/PU1_PE7.tcl
source macro_rpt/PU1_PE6.tcl
source macro_rpt/PU1_PE5.tcl
source macro_rpt/PU1_PE4.tcl
source macro_rpt/PU1_PE3.tcl
source macro_rpt/PU1_PE2.tcl
source macro_rpt/PU1_PE1.tcl
source macro_rpt/PU1_PE0.tcl
source macro_rpt/PU1_slave.tcl
source macro_rpt/PU2_PE3.tcl
source macro_rpt/PU2_PE2.tcl
source macro_rpt/PU2_PE1.tcl
source macro_rpt/PU2_PE0.tcl
source macro_rpt/PU2_PE7.tcl
source macro_rpt/PU2_PE6.tcl
source macro_rpt/PU2_PE5.tcl
source macro_rpt/PU2_PE4.tcl
source macro_rpt/PU2_PE11.tcl
source macro_rpt/PU2_PE10.tcl
source macro_rpt/PU2_PE9.tcl
source macro_rpt/PU2_PE8.tcl
source macro_rpt/PU2_PE12.tcl
source macro_rpt/PU2_PE13.tcl
source macro_rpt/PU2_PE14.tcl
source macro_rpt/PU2_PE15.tcl
source macro_rpt/PU2_slave.tcl
source macro_rpt/PU3_PE0.tcl
source macro_rpt/PU3_PE1.tcl
source macro_rpt/PU3_PE2.tcl
source macro_rpt/PU3_PE3.tcl
source macro_rpt/PU3_PE4.tcl
source macro_rpt/PU3_PE5.tcl
source macro_rpt/PU3_PE6.tcl
source macro_rpt/PU3_PE7.tcl
source macro_rpt/PU3_PE8.tcl
source macro_rpt/PU3_PE9.tcl
source macro_rpt/PU3_PE10.tcl
source macro_rpt/PU3_PE11.tcl
source macro_rpt/PU3_PE13.tcl
source macro_rpt/PU3_PE12.tcl
source macro_rpt/PU3_PE15.tcl
source macro_rpt/PU3_PE14.tcl
source macro_rpt/PU3_slave.tcl
source macro_rpt/read_buf.tcl
source macro_rpt/write_buf.tcl
