
# Constant to represent an ID (e.g. PE ID) that has not been set yet.
ID_UNDECIDED = -1
DEFAULT_NAMESPACE_BUFFER_SIZE = 8192
DEFAULT_BUS_BUFFER_SIZE = 512
DEFAULT_FLIP_FLOP_SIZE = 1

DEFAULT_INPUT_BITWIDTH = 16
DEFAULT_INTERIM_BITWIDTH = 32
DEFAULT_BUS_BITWIDTH = DEFAULT_INTERIM_BITWIDTH
DEFAULT_FLIP_FLOP_BITWIDTH = DEFAULT_INTERIM_BITWIDTH

DEFAULT_AXI_DATA_WIDTH = 64
DEFAULT_BURST_SIZE = 16

DEFAULT_NUM_AXI = 4
