set rtl_all {  
include/log.vh \
include/inst.vh \
include/config.vh \
include/weightInst.vh \
include/weight_insts.vh \
include/configurations.vh \
source/ALU/adder.v \
source/ALU/mac.v \
source/ALU/comparator.v \
source/ALU/divider.v \
source/ALU/sigmoid.v \
source/ALU/gaussian.v \
source/pe_compute.v \
source/basic/reg.v \
source/basic/buffer.v \
source/basic/bufferM.v \
source/basic/Cnter.v \
source/basic/rdFifo.v \
source/bram_stall.v \
source/comp_stall.v \
source/pe_namespace.v \
source/pe_namespace_wrapper.v \
source/pe_mem_interface.v \
source/basic/mux_2x1.v \
source/pe.v \
source/pe_empty.v \
source/pu.v \
source/accelerator.v \
source/operand_selector.v \
source/instCutter_new.v \
source/pe_controller_new.v \
source/decoder.v \
source/instruction_memory.v \
source/interim_buffer.v \
source/mem_interface/axim/wburst_counter.v \
source/mem_interface/axim/axi_master.v \
source/mem_interface/axim/axim_controller.v \
source/mem_interface/axis/axi_slave.v \
source/mem_interface/shifter.v \
source/mem_interface/if_control_new.v \
source/mem_interface/top/mem_interface.v \
source/mem_interface/mem_fifo/fifo.v \
source/mem_interface/mem_fifo/fifo_fwft.v \
source/basic/mux.v \
source/basic/ROM_ASIC.v \
source/tabla/tabla_wrapper.v \
source/pe_dummy.v \
source/bus_arbitrer/slave_controller.v \
source/bus_arbitrer/master_controller.v \
source/bus_arbitrer/fifo_bus.v \
source/bus_arbitrer/fifo_bus_read.v \
source/bus_arbitrer/bus_read.v \
source/bus_arbitrer/neigh_fifo.v \
source/basic/pipeline.v \
source/basic/bus_pipeline.v \
}  
